name: richa
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

  file_picker: ^5.2.2
  google_fonts: ^3.0.1
  font_awesome_flutter: ^10.2.1
  # path_provider: ^2.0.11
  #widgets_to_image: ^0.0.2

  cupertino_icons: ^1.0.2
  matrix4_transform: ^2.0.1
  screenshot: ^1.2.3

  # image_editor_pro: ^1.1.8
  
  json_annotation: ^4.4.0
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  json_serializable: ^6.2.0


flutter:
  uses-material-design: true
